language: node_js
node_js:
- node
before_script:
- npm install -g grunt-cli npm
env:
  global:
    secure: Ju/yVoKDz0SFijOglYHBORiumjqQB/XZ/sOWOQqfn61YoVAObw1lvQy36pm4H/3WoSsMIQ8XeoxwL9Y/pbWHrS7Opu/sW4umTRExJQuuarm9utlrdOEwaN+/c2luIWnMaQC6gbEXj6HnvZZqAAswxDhveYyq/wIxuTWN8xE884o6+KBOi2DJmLVurzYURfra9fP/rbeIN3iH/uAJYl9JfHIrfjhwslUpgXwmVTj+jh7jk8YkcCkQ+0bRWIIcAmmpKbmUZA5Zl5cBO6cHQAfsp6OYRvBw/H2pYYzkMJBJ//B1oVoYb5pcECPWe68pmX/EjocKYr6ZNcp0Hly21J7kuRDppui/f/uLWD2od0apUZGTyg2LkiejpxeEyEc1upa0tsrWO3q8Qr8kl3VQSfguGgAKAiQzB2zvAel+QEvnPzuslFPoh/WOIHDg02oi0Uc1dHEQk8XWGTLTnjI43qePVeoXmTERocfmn1OTyRoLEysHJxwCGsIZHxrhFCY3d7pzjKmsquWqXODnCVIx5U9wxG9P+la3K4ZOS/TaYVHvuAm81zrhjLDqrH7Rla6Jhx31DcagdtChJPp7zV6bkHsn5nW/hbpVgceew5Blc4KVI7BmFfx5ymogVD0gU1kYUxhNlsfhD+9DeaP5EX2qQjFOPW+ilWKB+ZtXqfT5jTLZNPI=
